import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import * as Cosmic from 'cosmicjs'
import Link from 'next/link';
const api = Cosmic();

const Home: NextPage = ({ students }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          All of our students
        </h1>
        {
          students != null &&
          students.map((student: any) => {
            <Link
              passHref
              key={student.name}
              href={`/student/${encodeURIComponent(student.slug)}`}
            >
              <div key={student.slug}>
                <div>{student.name}</div>
                <img src={student.student_headshot} height={250} width={250} alt={student.name} />
                <div>{student.major}</div>
                <div>{student.university}</div>
                <div>{student.story}</div>
              </div>
            </Link>
          })
        }
      </main>
    </div>
  )
}

export default Home

export async function getStaticProps() {
  const bucket = api.bucket({
    slug: process.env.BUCKET_SLUG,
    read_key: process.env.READ_KEY,
  })

  const students = await bucket.getObjects({
    query: {
      type: "students"
    },
    limit: 10
  })

  return {
    props: {
      students,
    },
  }
}
